xoofx/SharpYaml

SharpYaml.Tests/Serialization/SerializationTests2.cs
SharpYaml/Serialization/Serializers/PrimitiveSerializer.cs

This PR fixes #10 (reported by me a while back). There are two changes:
I added a field to "MyObject" of type decimal, and then added a decimal number into the string in the unit test "TestSimpleObjectAndPrimitive". This causes the test to *fail* due to #10.
Changed the format specifier for decimals from "R" (used for other *floating* precision types) and replaced it with format specifier "G" (used for other *fixed* precision types). This causes the test mentioned above to *pass*, thus fixing #10

Fixed failing decimal serialization

---

SharpYaml.Tests/YamlNodeTest.cs
SharpYaml/Model/YamlMapping.cs
SharpYaml/Model/YamlValue.cs

I added the overrides to make it easy to access YamlMapping by string values. But I found that this makes it impossible to use YamlValues with the same string value as distinct keys in a dictionary. So I'm removing the equality overrides and adding an on-demand string lookup table to YamlMapping.

Remove YamlValue equality overrides

---

SharpYaml.Tests/SharpYaml.Tests.csproj
SharpYaml.Tests/YamlNodeTrackerTest.cs
SharpYaml/Model/YamlDocument.cs
SharpYaml/Model/YamlMapping.cs
SharpYaml/Model/YamlNode.cs
SharpYaml/Model/YamlNodeTracker.cs
SharpYaml/Model/YamlSequence.cs
SharpYaml/Model/YamlStream.cs
SharpYaml/Model/YamlValue.cs

Instead of having events on each yaml object, which would be cumbersome and use more memory, the objects can be linked to a tracker object, which is notified of any changes to the YAML structure. The tracker object can either be supplied as an argument to a new `YamlStream` or an argument to the `Load` method.
The tracker only has one event, `TrackerEvent` for all changes to the hierarchy. The `TrackerEventArgs` has an `EventType` property, and can also be cast to specific event types, which have the same names as the value of the `EventType`.
The tracker tracks parent/child relationships, so that the subscribers to its events can know what yaml node is being modified. This is done through the `Path` struct, which stores the index of each child under its parent. In the case of a …

Add support for events and subscribers to be notified of model changes.

---

SharpYaml/Model/YamlNode.cs

I'm working on a system which is building type representations at runtime based on a schema which necessitated the need for a ToObject which takes a Type reference.

Expose new signature for YamlNode.ToObject which takes a Type reference.

---

SharpYaml.Tests/YamlNodeTrackerTest.cs
SharpYaml/Model/YamlDocument.cs
SharpYaml/Model/YamlMapping.cs
SharpYaml/Model/YamlNode.cs
SharpYaml/Model/YamlSequence.cs
SharpYaml/Model/YamlStream.cs

I was running into an issue when I would add a node with children to a document, and the children would not get tracked while the main node was.

When a node is made a child of a node with a tracker, assign the tracker to all of the children recursively.

---

SharpYaml/Directory.Build.props

This enabled SourceLink support the Microsoft new high performance version here:
https://github.com/dotnet/sourcelink/
I validated that it works with:
```
PS C:\Users\taggac\sourcelink\SourceLink\build> dotnet sourcelink test "C:\Users\taggac\sourcelink\SharpYaml\SharpYaml\bin\Release\SharpYaml.1.6.3.nupkg"
sourcelink test passed: lib/net35/SharpYaml.pdb
sourcelink test passed: lib/net45/SharpYaml.pdb
sourcelink test passed: lib/netstandard1.3/SharpYaml.pdb
sourcelink test passed: lib/netstandard1.6/SharpYaml.pdb
sourcelink test passed: lib/portable40-net40+sl5+win8+wp8+wpa81/SharpYaml.pdb
```

enable SourceLink

---

SharpYaml/Model/YamlNodeTracker.cs

Path.Resolve() is intended to function as a way to check if the given path is still valid when the data has changed, but I wasn't checking that the indices were still in range, so it was throwing exceptions.

ChildIndex.Resolve avoids OutOfRangeExceptions, returns null instead.

---

SharpYaml.Tests/ScannerTests.cs
SharpYaml.Tests/SharpYaml.Tests.csproj
SharpYaml.Tests/files/test15.yaml
SharpYaml/Scanner.cs

If a high surrogate character is found, look at the next character to see if they make a pair. If so, don't throw an exception and convert the pair to unicode.

Handle parsing unicode surrogate pairs.

---

SharpYaml.Tests/Serialization/SerializationTests2.cs
SharpYaml/Serialization/Serializers/DefaultObjectSerializerBackend.cs

It turned out that `DefaultObjectSerializerBackend.GetStyle` applied logic intended for primitive types only to all types (notice `|| !isPrimitiveElementType`), thus completely overriding any `DefaultStyle`.
This is to fix that, and add a corresponding test.

Fix serialization with DefaultStyle set to Flow (#70)

---

SharpYaml/Schemas/CoreSchema.cs
SharpYaml/Serialization/SerializerSettings.cs

I ran into a performance problem because I was deserializing individual leaf nodes of a YAML file using `YamlNode.ToObject`, and so I was creating a new `SerializerSettings` every time. As a result, `PrepareScalarRules` in `CoreSchema` ran over and over and was a big performance hit. This solves that problem.

Make CoreSchema a singleton so that PrepareScalarRules only runs once.

---

src/SharpYaml.Tests/Serialization/SerializationTests.cs
src/SharpYaml/Emitter.cs
src/SharpYaml/Serialization/Serializer.cs

Not sure what to do for the case of complex keys, but they're probably not valid JSON anyway.

Always enclose keys in quotes when emitting JSON.

---

src/SharpYaml/Serialization/SerializerSettings.cs

This would be binary compatible with previous versions, while making the 
new fixed member the only one visible for newer users of the API.

Fix EmitJsonComptible typo by hiding old member and adding fixed one

---

src/SharpYaml.Tests/EmitterTests.cs
src/SharpYaml.Tests/ParserTests.cs
src/SharpYaml.Tests/ScannerTests.cs
src/SharpYaml.Tests/Serialization/SerializationTests.cs
src/SharpYaml/CharacterAnalyzer.cs
src/SharpYaml/Emitter.cs
src/SharpYaml/Events/DocumentStart.cs
src/SharpYaml/Events/MappingStart.cs
src/SharpYaml/Events/Scalar.cs
src/SharpYaml/Events/SequenceStart.cs
src/SharpYaml/Events/StreamStart.cs
src/SharpYaml/ILookAheadBuffer.cs
src/SharpYaml/Mark.cs
src/SharpYaml/Model/YamlDocument.cs
src/SharpYaml/Model/YamlMapping.cs
src/SharpYaml/Model/YamlNode.cs
src/SharpYaml/Model/YamlNodeEventEnumerator.cs
src/SharpYaml/Model/YamlNodeTracker.cs
src/SharpYaml/Model/YamlSequence.cs
src/SharpYaml/Model/YamlStream.cs
src/SharpYaml/Model/YamlValue.cs
src/SharpYaml/Parser.cs
src/SharpYaml/Scanner.cs
src/SharpYaml/Serialization/Serializer.cs
src/SharpYaml/Serialization/YamlStream.cs
src/SharpYaml/StringLookAheadBuffer.cs

Performance improvement to use StringLookaheadBuffer where a string can be directly accessed. This proves important especially with YAML that has a lot of quoted values that makes heavy use of ScanFlowScalar.
This is a before and after comparison in DotTrace using Sample mode:
This is using Tracing mode:

Use StringLookaheadBuffer if a string is available.

---

src/SharpYaml.Tests/PathTrieTest.cs
src/SharpYaml.Tests/YamlNodeTrackerTest.cs
src/SharpYaml/Model/PathTrie.cs
src/SharpYaml/Model/YamlMapping.cs
src/SharpYaml/Model/YamlNodeTracker.cs
src/SharpYaml/Model/YamlSequence.cs
src/SharpYaml/Model/YamlStream.cs

This is a bug that took me a while to diagnose. After modifying a container, the modification events were giving me incorrect paths to the item which was modified.
Also fixed YamlMapping's enumerator to return items in the same order as the keys.

When an item is inserted/removed from a container, update the indices of the subsequent children in the tracker.

---

src/SharpYaml/SharpYaml.csproj

This dependency isn't necessary for NS2, as noted by @xoofx in #54.
Fixes #54 and also makes it usable under MSBuild when targeting NS2 :)

Remove dependency on System.Reflection.TypeExtensions from netstandad2.0

---

src/SharpYaml.Tests/Serialization/SerializationTests2.cs
src/SharpYaml/Serialization/SerializerSettings.cs
src/SharpYaml/Serialization/Serializers/ObjectSerializer.cs

Adding a optional setting for serializer to ignore serialization of properties with null values.

Add option to serializer settings to ignore null values

---

src/SharpYaml/CharHelper.cs
src/SharpYaml/Model/YamlNodeTracker.cs
src/SharpYaml/Serialization/AssemblyRegistry.cs
src/SharpYaml/Serialization/DefaultObjectFactory.cs
src/SharpYaml/Serialization/Descriptors/ObjectDescriptor.cs
src/SharpYaml/Serialization/Serializers/PrimitiveSerializer.cs
src/SharpYaml/SharpYaml.csproj
src/SharpYaml/TypeExtensions.cs

- Remove old code older than .netstandard2.0
- Make use of `Array.Empty()`.
- Simplify null calls.

Code cleanup

---

src/SharpYaml.Tests/Serialization/SerializationTests.cs
src/SharpYaml.Tests/Serialization/SerializationTests2.cs
src/SharpYaml.Tests/YamlNodeTest.cs
src/SharpYaml/Serialization/AssemblyRegistry.cs
src/SharpYaml/Serialization/SerializerSettings.cs

- `SerializerSettings.UnsafeAllowDeserializeFromTagTypeName` is added.
- `SerializerSettings.EmitTags` is set to false by default. (for roundtrip)
- Calling `SerializerSettings.RegisterAssembly` or `SerializerSettings.RegisterTagMapping`, sets `EmitTags` to true.

Tag type names in payloads are no longer respected by default.

---

src/SharpYaml/Serialization/YamlMemberAttribute.cs

This PR adds a new constructor to YamlMemberAttribute that allows both name and order to be specified. Since DefaultKeyComparer already looks for Order.HasValue first and then falls back to Name, both can be specified on the same member.
This PR resolves #42 which did not allow Order to be specified as an attribute parameter since int? triggered a [CS0655 compiler error](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0655).
I did verify that all tests still pass before submitting this pull requests.

Added named order constructor to YamlMemberAttribute.

---

src/SharpYaml.Tests/Serialization/SerializationTests2.cs
src/SharpYaml/Serialization/Serializers/ScalarSerializerBase.cs

Fixes #106
Also fixes quoting for integer values in strings.
I guess the double.TryParse was an optimization to avoid parsing long string values if unnecessary? If so, this might impact performance when serializing a lot of longer string values. Might add similar parsing attempts for bools and integers (null check is trivial), but not sure if C# parsers match the YAML spec exactly.

Force double quotes on integers and null in string

---

src/SharpYaml.Tests/Serialization/SerializationTests2.cs
src/SharpYaml/Serialization/Serializer.cs
src/SharpYaml/Serialization/SerializerSettings.cs
src/SharpYaml/Serialization/Serializers/AnchorSerializer.cs

Changes made according to the indications of https://github.com/xoofx/SharpYaml/issues/115#issuecomment-1206198558
The tests were not very clear where to put them since there are SerializationTests and SerializationTests2, if you have any suggestion and you want me to change it, let me know.

Allow reuse of Serializer instance

---

.github/workflows/ci.yml
src/SharpYaml.Tests/Serialization/SerializationTests.cs
src/SharpYaml.Tests/SharpYaml.Tests.csproj
src/SharpYaml/Serialization/Serializers/ObjectSerializer.cs
src/global.json

Fix IgnoreUnmatchedProperties for map types
